name: conan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: os info
      run: uname -m
    - name: conan install
      run: conan install ZenGitHub/1.0@jonico/stable --build missing
