name: React on flic button
on: [repository_dispatch]

jobs:
  react-on-flic-button:
    runs-on: ubuntu-latest
    if:  startsWith(github.event.action, 'flic')
    steps:
    - name: Hold - Merge pull request
      if:  github.event.action == 'flic-hold'
      uses: actions/github-script@0.5.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.pulls.merge({
            pull_number: 31,
            owner: context.repo.owner,
            repo: context.repo.repo,
          })
